# Generated by Django 5.2.7 on 2025-10-12 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_buyer_location_maintenancestaff_supplier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetvaluation',
            name='asset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asset_valuation', to='api.asset'),
        ),
    ]
