# Generated by Django 5.2.7 on 2025-10-15 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_assetvaluation_asset'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('staff', 'Staff')], default='staff', max_length=30),
        ),
    ]
